import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <header className="App-header">
                    <Link href={"/"}>Home</Link>
                    <Link href={"/login"}>Sign in</Link>
                    <Link href={"/list"}>Your Lists</Link>
                    <Link href={"/list/1"}>View List</Link>
                </header>
                {children}
            </body>
        </html>
    );
}
